# Generated by Django 4.2.5 on 2023-10-13 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='footballPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('goals', models.IntegerField()),
                ('jerseynumber', models.IntegerField()),
                ('team', models.CharField(max_length=25)),
                ('NumberofMatches', models.IntegerField()),
            ],
        ),
    ]
